= Lightsleep リリース･ノート

link:ReleaseNotes.asciidoc[English]

[[TOC_]]
=== 目次

- <<ReleaseNote3.0.0,バージョン 3.0.0>>
- <<ReleaseNote2.2.1,バージョン 2.2.1>>
- <<ReleaseNote2.2.0,バージョン 2.2.0>>
- <<ReleaseNote2.1.1,バージョン 2.1.1>>
- <<ReleaseNote2.1.0,バージョン 2.1.0>>
- <<ReleaseNote2.0.0,バージョン 2.0.0>>

[[ReleaseNote3.0.0]]

=== バージョン3.0.0

1. **改善**
  * 以下のデータ型をサポートしました。エンティティクラスのフィールド型として使用できます。
    ** `java.time.LocalDate`
    ** `java.time.LocalTime`
    ** `java.time.LocalDateTime`
    ** `java.time.OffsetDateTime`
    ** `java.time.ZonedDateTime`
    ** `java.time.Instant`

1. **追加**されたメソッドおよびコンストラクタ
  * `org.lightsleep.**Sql**` クラス
    ** `**doNotIf**(boolean condition, Consumer<Sql<E>> action)`
    ** `**doElse**(Consumer<Sql<E>> elseAction)`
    ** `**executeUpdate**(String sql)`

  * `org.lightsleep.database.**Database**` インタフェースおよびこれをインプリメントしているクラス
    ** `**getObject**(Connection connection, ResultSet resultSet, String columnLabel)`

  * `org.lightsleep.helper.ConvertException` クラス
    ** `**ConvertException**(Class<?> sourceType, Object source, Class<?> destinType, Throwable cause)`

  * `org.lightsleep.helper.TypeConverter` クラス
    ** `**TypeConverter**(Class<ST> sourceType, Class<DT> destinType, Function<? super ST, MT> function1, Function<? super MT, ? extends DT> function2)`
    ** `**TypeConverter**(Class<ST> sourceType, Class<DT> destinType,Function<? super ST, ? extends MT1> function1, Function<? super MT1, ? extends MT2> function2, Function<? super MT2, ? extends DT> function3)`
    ** `**TypeConverter**(Class<ST> sourceType, Class<DT> destinType, Function<? super ST, MT1> function1, Function<? super MT1, ? extends MT2> function2, Function<? super MT2, ? extends MT3> function3, Function<? super MT3, ? extends DT> function4)`

1. **非推奨**になったメソッド
  * `org.lightsleep.**Sql**` クラス
    ** `**doIf**(boolean condition, Consumer<Sql<E>> action, Consumer<Sql<E>> elseAction)`

1. **削除**されたメソッドおよびコンストラクタ
  * `org.lightsleep.**Sql**` クラス

    ** `**select**(ConnectionWrapper connection, Consumer<? super E> consumer)`
    ** `**select**(ConnectionWrapper connection, Consumer<? super E> consumer, Consumer<? super JE1> consumer1)`
    ** `**select**(ConnectionWrapper connection, Consumer<? super  E > consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2)`
    ** `**select**(ConnectionWrapper connection, Consumer<? super E> consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2, Consumer<? super JE3> consumer3)`
    ** `**select**(ConnectionWrapper connection, Consumer<? super E> consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2, Consumer<? super JE3> consumer3, Consumer<? super JE4> consumer4)`
    ** `**select**(ConnectionWrapper connection)`
    ** `**selectCount**(ConnectionWrapper connection)`
    ** `**insert**(ConnectionWrapper connection, E entity)`
    ** `**insert**(ConnectionWrapper connection, Iterable<? extends E> entities)`
    ** `**update**(ConnectionWrapper connection, E entity)`
    ** `**update**(ConnectionWrapper connection, Iterable<? extends E> entities)`
    ** `**delete**(ConnectionWrapper connection)`
    ** `**delete**(ConnectionWrapper connection, E entity)`
    ** `**delete**(ConnectionWrapper connection, Iterable<? extends E> entities)`

  * `org.lightsleep.database.**DB2**`, `**MySQL**`, `**Oracle**`, `**PostgreSQL**`, `**SQLite**`, `**SQLServer**`, `**Standard**` クラス
    ** `instance()`

  * `org.lightsleep.helper.TypeConverter` クラス
    ** `**TypeConverter**(TypeConverter<ST, MT> typeConverter1, TypeConverter<MT, DT> typeConverter2)`

<<TOC_,目次へ>>

[[ReleaseNote2.2.1]]

=== バージョン2.2.1

1. バグ修正
  * [修正済] OracleのJDBCドライバjarがクラスパスにないと動作しない。

<<TOC_,目次へ>>

[[ReleaseNote2.2.0]]

=== バージョン2.2.0

1. 改善
  * SQLのログに接続先のJDBC URLを含めるオプションを*追加*しました。 +
    使用例:::
    `lightsleep.properties`ファイルに以下を追加 +
    `connectionLogFormat = [{0}/{1}/{2}]`

  * ログのパスワード部分を`"xxxx"`でマスクするようにしました。

1. `Database`インタフェースおよびその実装クラスに`maskPassword`メソッドを*追加*しました。

<<TOC_,目次へ>>

[[ReleaseNote2.1.1]]

=== バージョン2.1.1

1. バグ修正
  * [修正済] コネクション･サプライヤが`Jndi`の場合に常に`Standardデータベース･ハンドラが選択される。

1. その他
  * ログメッセージの改善

<<TOC_,目次へ>>

[[ReleaseNote2.1.0]]

=== バージョン2.1.0

バージョン番号はマイナー･リリースですが、**仕様変更があります**。

1. `lightsleep.properties`ファイルに、複数のJDBC URLの定義を**可能**にしました。

1. JDBC URLに対応するデータベース･ハンドラ･クラス**は自動的に判断**されるようになりました。これに伴い`lightsleep.properties`ファイルの`Database`プロパティを**無効**にしました。**(仕様変更)**

1. 以下のメソッド/コンストラクタを**追加**しました。
  * Sqlクラス
    ** public ConnectionWrapper getConnection()

  * org.lightsleep.connection.ConnectionSupplierインタフェース
    ** Database getDatabase()
    ** DataSource getDataSource()
    ** String getUrl()
    ** static ConnectionSupplier of(String supplierName, Properties properties)
    ** static ConnectionSupplier find(String... urlWords)

  * org.lightsleep.connection.AbstractConnectionSupplier抽象クラス
    ** protected AbstractConnectionSupplier(Properties properties, Consumer<Properties> modifier)
    ** @Override public Database getDatabase()
    ** @Override public String getUrl()
    ** @Override public String toString()

  * org.lightsleep.database.Databaseインタフェース
    ** static Database getInstance(String jdbcUrl)

  * org.lightsleep.helper.Resourceクラス
      * public static Resource getGlobal()

1. `org.lightsleep.Sql`クラスの以下のメソッドを**削除**しました。**(仕様変更)**
  * public static Database getDatabase()
  * public static void setDatabase(Database database)
  * public static ConnectionSupplier getConnectionSupplier()
  * public static void setConnectionSupplier(ConnectionSupplier supplier)

1. `org.lightsleep.connection.ConnectionWrapper`クラスを追加し、各メソッドの引数の型を`java.sql.Connection`から`ConnectionWrapper`に**変更**しました。**(仕様変更)**

1. `org.lightsleep.connection`パッケージの各クラスに`Properties properties`を引数とするコンストラクタを**追加**しました。

1. `org.lightsleep.database.anchor`パッケージと`db2`, `mysql`, `oracle`, `postgresql`, `sqlite`, `sqlserver`クラスを**追加**しました。これらのクラスは、JDBC URLから対応するデータベース･ハンドラ･クラスを見つける際に使用されます。

1. `org.lightsleep.database`パッケージの各クラスの`instance()`メソッドを**非推奨**にし、`instance`静的変数を**追加**しました。

<<TOC_,目次へ>>

[[ReleaseNote2.0.0]]

=== バージョン2.0.0

1. `org.lightsleep.Sql`クラスの型パラメータとは異なるエンティティ型でSELECT SQLの結果を取得する以下のメソッドを**追加**しました。
  * public <R> Optional<R> selectAs(Class<R> resultClass)
  * public <R> void selectAs(Class<R> resultClass, Consumer<? super R> consumer)

1. `org.lightsleep.Sql`クラスの`Connection`引数を持つメソッドを**非推奨**にし、`Connection`引数がない以下のメソッドを**追加**しました。
  * public void select(Consumer<? super E> consumer)
  * public <JE1> void select(Consumer<? super E> consumer, Consumer<? super JE1> consumer1)
  * public <JE1, JE2> void select(Consumer<? super E> consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2)
  * public <JE1, JE2, JE3> void select(Consumer<? super  E> consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2, Consumer<? super JE3> consumer3)
  * public <JE1, JE2, JE3, JE4> void select(Consumer<? super E> consumer, Consumer<? super JE1> consumer1, Consumer<? super JE2> consumer2, Consumer<? super JE3> consumer3, Consumer<? super JE4> consumer4)
  * public Optional<E> select()
  * public int selectCount()
  * public int insert(E entity)
  * public int insert(Iterable<? extends E> entities)
  * public int update(E entity)
  * public int update(Iterable<? extends E> entities)
  * public int delete()
  * public int delete(E entity)
  * public int delete(Iterable<? extends E> entities)

1. `org.lightsleep.Sql`クラスに以下のメソッドを**追加**しました。
  * public Sql<E> connection(Connection connection)
  * public <R> Sql<E> setColumns(Class<R> resultClass)
  * public Sql<E> doAlways(Consumer<Sql<E>> action)

1. `org.lightsleep.Sql`クラスが`Cloneable`インタフェースを**実装**するようにしました。

1. `org.lightsleep.Sql`クラスの`where`メソッドの引数の仕様を**変更**しました。**(仕様変更)**
    ```
    public Sql<E> where(E entity)
        ↓
    public <K> Sql<E> where(K entity)
    ```

1. `Table`アノテーション･クラスに付与されていた`@Inherited`を**削除**しました。**(仕様変更)**

1. `Key`, `NonColumn`, `NonInsert`, `NonSelect`, `NonUpdate`アノテーション･クラスに`value`プロパティを**追加**しました。

1. `NonColumnProperty`, `NonInsertProperty`, `NonSelectProperty`, `NonUpdateProperty`アノテーション･クラスに`property`プロパティを**追加**し、`value`プロパティの仕様を**変更**しました。**(仕様変更)**

1. `org.lightsleep.component.Expression`クラスの`toString`において、内容文字列の`{}`と引数の数が不一致の際にスローする例外を`IllegalArgumentException`から`MissingArgumentsException`(新規追加)に**変更**にしました。**(仕様変更)**

1. `org.lightsleep.helper.Accessor`クラスの`getField`, `getValue`, `setValue`メソッドでスローする例外を`IllegalArgumentException`から`MissingPropertyException`(新規追加)に**変更**にしました。**(仕様変更)**

<<TOC_,目次へ>>

[gray]#_(C) 2016 Masato Kokubo_#
