= Lightsleep Tutorial

link:Tutorial_ja.asciidoc[Japanese]

Let's create a simple program that gets rows from the table and output to the console.

==== 1. Preparing the table

Create the Contact table to any database in DB2, MySQL, Oracle, PostgreSQL, SQLite or SQL Server, and then insert the sample data.

Create a table using one of the following SQL.

[source,sql]
.ddl_db2.sql - DB2
----
CREATE TABLE Contact (
    id        INTEGER        NOT NULL,
    firstName VARGRAPHIC(20) NOT NULL,
    lastName  VARGRAPHIC(20) NOT NULL,
    birthday  DATE               NULL,

    PRIMARY KEY(id)
);
----

[source,sql]
.ddl_mysql.sql - MySQL
----
CREATE TABLE Contact (
    id         INT         NOT NULL,
    firstName  VARCHAR(20) NOT NULL,
    lastName   VARCHAR(20) NOT NULL,
    birthday   DATE            NULL,

    PRIMARY KEY(id)
);
----

[source,sql]
.ddl_oracle.sql - Oracle
----
CREATE TABLE Contact (
    id         NUMBER  ( 9)      NOT NULL,
    firstName  VARCHAR2(20 CHAR) NOT NULL,
    lastName   VARCHAR2(20 CHAR) NOT NULL,
    birthday   DATE                  NULL,

    PRIMARY KEY(id)
);
----

[source,sql]
.ddl_postgresql.sql - PostgreSQL
----
CREATE TABLE Contact (
    id         INT         NOT NULL,
    firstName  VARCHAR(20) NOT NULL,
    lastName   VARCHAR(20) NOT NULL,
    birthday   DATE            NULL,

    PRIMARY KEY(id)
);
----

[source,sql]
.ddl_sqlite.sql - SQLite
----
CREATE TABLE Contact (
    id        INTEGER     NOT NULL,
    firstName VARCHAR(20) NOT NULL,
    lastName  VARCHAR(20) NOT NULL,
    birthday  TEXT            NULL,

    PRIMARY KEY(id)
);
----

[source,sql]
.ddl_sqlserver.sql - SQLServer
----
CREATE TABLE Contact (
    id         INT         NOT NULL,
    firstName  VARCHAR(20) NOT NULL,
    lastName   VARCHAR(20) NOT NULL,
    birthday   DATE            NULL,

    PRIMARY KEY(id)
);
----

Execute the following SQL to insert the data into the table.

[source,sql]
.sample.sql
----
DELETE FROM Contact;
INSERT INTO Contact VALUES (1, 'First' , 'Example', DATE'1991-01-01');
INSERT INTO Contact VALUES (2, 'Second', 'Example', DATE'1992-02-02');
INSERT INTO Contact VALUES (3, 'Third' , 'Example', DATE'1993-03-03');
INSERT INTO Contact VALUES (4, 'Fourth', 'Example', DATE'1994-04-04');
----

==== 2. Creating the entity class

Create the entity class to hold rows obtained from the Contact table.

[source,java]
.Contact.java
----
package org.lightsleep.tutorial.entity;

import java.sql.Date;

import org.lightsleep.entity.*;

/**
 * Contact entity
 */
public class Contact {
    /** Contact ID */
    @Key
    public Integer id;

    /** First Name */
    public String firstName;

    /** Last Name */
    public String lastName;

    /** Birthday */
    public Date birthday;
}
----

==== 3. Preparation of properties file

Create `lightsleep.properties` file below and place one of the class paths. Change to match the database environment to use the value of `url`, `user` and `password`.

[source,properties]
.lightsleep.properties - DB2
----
url      = jdbc:db2://<Database Server>:50000/<Database>
user     = <User Name>
password = <Password>
----

[source,properties]
.lightsleep.properties - MySQL
----
url      = jdbc:mysql://<Database Server>/<Database>
user     = <User Name>
password = <Password>
----

[source,properties]
.lightsleep.properties - Oracle
----
url      = jdbc:oracle:thin:@<Database Server>:1521:<SID>
user     = <User Name>
password = <Password>
----

[source,properties]
.lightsleep.properties - PostgreSQL
----
url      = jdbc:postgresql://<Database Server>/<Database>
user     = <User Name>
password = <Password>
----

[source,properties]
.lightsleep.properties - SQLite
----
url = jdbc:sqlite:<Installed Directory>/<Database>
----

[source,properties]
.lightsleep.properties - SQL Server
----
url      = jdbc:sqlserver://<Database Server>;Database=<Database>
user     = <User Name>
password = <Password>
----

==== 4. Getting data
Create a program to retrieve all the rows from the table.

[source,java]
.Example1.java
----
package org.lightsleep.tutorial;

import java.util.ArrayList;
import java.util.List;

import org.lightsleep.Sql;
import org.lightsleep.Transaction;
import org.lightsleep.tutorial.entity.Contact;

public class Example1 {
    public static void main(String[] args) {
        try {
            List<Contact> contacts = new ArrayList<>();
            Transaction.execute(conn -> {
                new Sql<>(Contact.class).connection(conn)
                    .select(contacts::add);
            });

            for (int index = 0; index < contacts.size(); ++index) {
                Contact contact = contacts.get(index);
                System.out.println(
                    index
                    + ": Name: " + contact.firstName + " " + contact.lastName
                    + ", Birthday: " + contact.birthday
                );
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}
----

When you run the Example1 following is displayed on the console.

[source,log]
.stdout
----
    ...
    ...
    ...
0: Name: First Example, Birthday: 1991-01-01
1: Name: Second Example, Birthday: 1992-02-02
2: Name: Third Example, Birthday: 1993-03-03
3: Name: Fourth Example, Birthday: 1994-04-04
----

[gray]#_(C) 2016 Masato Kokubo_#
